const TODOS_PREFIX = "[TODOS] ";

const todos = {
    FETCH_TODOS: TODOS_PREFIX.concat("FETCH_TODOS"),
    SUCCESS_TODOS: TODOS_PREFIX.concat("SUCCESS_TODOS"),
    FAILED_TODOS: TODOS_PREFIX.concat("FAILED_TODOS"),
    ADD_TODO: TODOS_PREFIX.concat("ADD_TODO"),
    ADD_TODO_SUCCESS: TODOS_PREFIX.concat("ADD_TODO_SUCCESS"),
    ADD_TODO_FAILED: TODOS_PREFIX.concat("ADD_TODO_FAILED"),
    DELETE_TODO: TODOS_PREFIX.concat("DELETE_TODO"),
    DELETE_TODO_SUCCESS: TODOS_PREFIX.concat("DELETE_TODO_SUCCESS"),
    DELETE_TODO_FAILED: TODOS_PREFIX.concat("DELETE_TODO_FAILED"),
    TOGGLE_TODO: TODOS_PREFIX.concat("TOGGLE_TODO"),
    TOGGLE_TODO_SUCCESS: TODOS_PREFIX.concat("TOGGLE_TODO_SUCCESS"),
    TOGGLE_TODO_FAILED: TODOS_PREFIX.concat("TOGGLE_TODO_FAILED"),
};

export { todos };
